[project]
name = "api-demo"
version = "0.1.0"
dependencies = [
  "requests",
  "click"
]
requires-python = ">= 3.11"

[project.scripts]
bird = "main:lookup_num"
album = "main:get_photos"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
